### ISSUE TITLE
devfs.rules

### ISSUE THREAD

**Issue by myfreeweb** [t6/freebsd-runit#2]
Looks like devfs rules are applied with shell functions in rc.subr and rc.d/devfs, I can't think of a better way than just calling `service devfs start`…

hmm, I wonder what TrueOS does with this for OpenRC

**Comment by t6** [comment]
I've added a `41-devfs-rules.sh` core service.  Can you give a try and see what breaks?

If you currently have something like `devfs_system_ruleset=localrules` in rc.conf, you'll have to put something like
```
[runit_devfs_rules=42]
add include $localrules
```
into `/etc/devfs.rules`.

**Comment by myfreeweb** [comment]
Works fine, thanks!
