### ISSUE TITLE
Reboot/poweroff weirdness

### ISSUE THREAD

**Issue by myfreeweb** [t6/freebsd-runit#5]
When booted with runit, the `reboot` command powers the system down, the `poweroff` command only sends the shutdown log message and does nothing, the (acpi) power button does nothing.

On two different machines..

**Comment by t6** [comment]
Yes, sorry for POLA violation but I cannot change FreeBSD's reboot command. It only supports init(8). It does not support runit's `/etc/runit/{reboot,stopit}` weirdness (see runt-init(8)). This is documented in runit-faster(7). Use `runit-init 6` to reboot and `runit-init 0` to shutdown/poweroff.

If you use ConsoleKit you can [now](https://svnweb.freebsd.org/ports?view=revision&revision=496800) edit `/usr/local/lib/ConsoleKit/scripts/ck-system-{restart,stop}` to also call these. I did not find this to be much of a problem for me personally after that. YMMV.

ACPI power button is configured to suspend the machine for me. Not sure about what FreeBSD does when ACPI power button is pressed with `hw.acpi.power_button_state=S5`. Probably we need to add a `etc/devd/runit-faster.conf` or something to do something about that?

**Comment by myfreeweb** [comment]
> It only supports init(8)

oh.. I completely forgot that reboot is an init thing. And apparently I can't read. Sorry for the spam haha.

I guess you can install a `/usr/local/sbin/reboot` but that is also questionable in terms of POLA.

> If you use ConsoleKit

well, not for shutdown right now, only for [getting drm/evdev devices](https://reviews.freebsd.org/D18754). My ["DE" project](https://github.com/myfreeweb/numbernine) does not have a shutdown button yet, I use shell commands :D

> Not sure about what FreeBSD does when ACPI power button is pressed with hw.acpi.power_button_state=S5

Turns out `shutdown_nice` which.. also signals init. "S5 (soft-off) should be entered directly with no waiting" — i.e. it even skips the devd suspend notification. Though the button itself is a separate notification and we could handle that / actually DEs might want to handle that to present a dialog..

**Comment by t6** [comment]
> Turns out shutdown_nice which.. also signals init.

Hmm, thanks for that. It actually seems to send SIGUSR2 to pid 1 on RB_POWEROFF which we might be able to catch by patching `runit.c`. Let me try that.

**Comment by t6** [comment]
This seems to work: https://people.freebsd.org/~tobik/patches/runit-faster-usr2.diff

Can you test?
