### ISSUE TITLE
Don't run loggers as root

### ISSUE THREAD

**Issue by myfreeweb** [t6/freebsd-runit#7]
Looks like `exec chpst -u nobody:nogroup logger …` works fine

**Comment by t6** [comment]
Why is running logger as root a problem? It barely does anything.

**Comment by myfreeweb** [comment]
Maybe not really much of a *problem* but like… it doesn't *need* root, so https://en.wikipedia.org/wiki/Principle_of_least_privilege

**Comment by t6** [comment]
You can add `chpst -u nobody:nogroup` to `etc/runit/logger` now if you want. If you think that logger needs privsep or other sandboxing maybe it can be done in FreeBSD base.

**Comment by myfreeweb** [comment]
ooh, a wrapper script is nice, thanks
